import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import '../../models/allergen.dart';
import '../../providers/allergy_profile_provider.dart';
import '../../core/theme.dart';

class EmergencyCardScreen extends ConsumerWidget {
  const EmergencyCardScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final allergens = ref.watch(allergyProfileProvider);
    final screenshotController = ScreenshotController();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Emergency Card'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Share card',
            onPressed: () => _shareCard(context, screenshotController, allergens),
          ),
        ],
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Screenshot(
            controller: screenshotController,
            child: _EmergencyCard(allergens: allergens),
          ),
        ),
      ),
    );
  }

  Future<void> _shareCard(
    BuildContext context,
    ScreenshotController controller,
    List<Allergen> allergens,
  ) async {
    final imageBytes = await controller.capture(pixelRatio: 3.0);
    if (imageBytes == null) return;

    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/safebite_emergency_card.png');
    await file.writeAsBytes(imageBytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'My food allergy card from SafeBite',
    );
  }
}

class _EmergencyCard extends StatelessWidget {
  final List<Allergen> allergens;
  const _EmergencyCard({required this.allergens});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    // Group by severity
    final severe = allergens.where((a) => a.severity == Severity.severe).toList();
    final moderate = allergens.where((a) => a.severity == Severity.moderate).toList();
    final mild = allergens.where((a) => a.severity == Severity.mild).toList();

    return Card(
      elevation: 4,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [Colors.white, Colors.grey.shade50],
          ),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.medical_services, color: AppTheme.dangerColor, size: 28),
                const SizedBox(width: 8),
                Text(
                  'FOOD ALLERGY ALERT',
                  style: theme.textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: AppTheme.dangerColor,
                    letterSpacing: 1.2,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text(
              'Please read carefully',
              style: theme.textTheme.bodyMedium?.copyWith(color: Colors.grey),
            ),
            const Divider(height: 32),

            // Severe
            if (severe.isNotEmpty) ...[
              _SeveritySection(
                title: 'SEVERE (Anaphylaxis Risk)',
                allergens: severe,
                color: AppTheme.dangerColor,
                bgColor: AppTheme.dangerBg,
              ),
              const SizedBox(height: 16),
            ],

            // Moderate
            if (moderate.isNotEmpty) ...[
              _SeveritySection(
                title: 'MODERATE',
                allergens: moderate,
                color: const Color(0xFFE65100),
                bgColor: const Color(0xFFFFF3E0),
              ),
              const SizedBox(height: 16),
            ],

            // Mild
            if (mild.isNotEmpty) ...[
              _SeveritySection(
                title: 'MILD',
                allergens: mild,
                color: AppTheme.cautionColor,
                bgColor: AppTheme.cautionBg,
              ),
              const SizedBox(height: 16),
            ],

            const Divider(),
            const SizedBox(height: 8),
            Text(
              'Generated by SafeBite',
              style: theme.textTheme.bodySmall?.copyWith(color: Colors.grey),
            ),
          ],
        ),
      ),
    );
  }
}

class _SeveritySection extends StatelessWidget {
  final String title;
  final List<Allergen> allergens;
  final Color color;
  final Color bgColor;

  const _SeveritySection({
    required this.title,
    required this.allergens,
    required this.color,
    required this.bgColor,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 13,
            color: color,
            letterSpacing: 0.5,
          ),
        ),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: allergens.map((a) => Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
            decoration: BoxDecoration(
              color: bgColor,
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: color.withValues(alpha: 0.3)),
            ),
            child: Text(
              '${a.emoji}  ${a.displayName}',
              style: TextStyle(
                color: color,
                fontWeight: FontWeight.w600,
                fontSize: 15,
              ),
            ),
          )).toList(),
        ),
      ],
    );
  }
}
